### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by EddieLavian** [EddieLavian/FinalProject-2B#2]
- [x] github

- [x] Diary

- [ ] Use Case

- [x] Market Survey

- [x] Flow Chart

- [ ] Sequence Diagram

- [ ] UML

- [ ] Relation Table

**Comment by TalYehoshua** [comment]
Proposal Updated by Eddie.
more updates will be made soon.

**Comment by EddieLavian** [comment]
The other things on the chck list move to alpha version.
The proposal file is done
