### ISSUE TITLE
Main activity

### ISSUE THREAD

**Issue by EddieLavian** [EddieLavian/FinalProject-2B#4]
Main Activity example : 
![main activity](https://user-images.githubusercontent.com/26080528/32866219-3619743c-ca6f-11e7-97e3-c58f2433387c.png)

- [x] My Teams

- [x] Open Teams

- [x] Massages and updates

- [x] Weather

- [x] Chat

**Comment by TalYehoshua** [comment]
Weather need to fix

**Comment by EddieLavian** [comment]
Done!
