### ISSUE TITLE
Profile activity

### ISSUE THREAD

**Issue by EddieLavian** [EddieLavian/FinalProject-2B#5]
Profile activity example:
![profile activity](https://user-images.githubusercontent.com/26080528/32866397-5155d15e-ca70-11e7-9227-d8d2ac03050a.png)

- [x] picture

- [x] personal details

- [x] 3 buttons: 
- My teams
- Personal statistics
- update and settings

**Comment by TalYehoshua** [comment]
To Do:
- Personal statistics
- update

**Comment by TalYehoshua** [comment]
Side bar:
update username, photo, teams edit.

remove: personal chat

**Comment by EddieLavian** [comment]
personal chat removed.

Need to do:

1. Personal Statistics

2. Upcoming games

3. Side bar
