### ISSUE TITLE
Side bar

### ISSUE THREAD

**Issue by EddieLavian** [EddieLavian/FinalProject-2B#7]
- [x] Logout

- [x] Profile update

- [x] Tournament

- [x] Contact Us

**Comment by TalYehoshua** [comment]
logout ready

**Comment by TalYehoshua** [comment]
Need to add profile to side bar

**Comment by EddieLavian** [comment]
profile added. need to functional it to profile page..

And to change the location of the side bar

**Comment by EddieLavian** [comment]
profile Done!

Now need to add 'about us'
